---
title: "A Little Life Update"
author: "Seongbin Park"
categories: [misc]
page-layout: article
description: A little update on my life
date: "2024-11-03"
---

So around 8 months ago, I did the thing: being done with school. Yes, I walked in June and yes, I still haven't picked up my diploma, but on March 19th, I took my last exam. I think I turned in my last paper on the 21st, but I'm not exactly sure on that. But yeah. Just like that, I was done with my last quarter of my undergraduate career. Didn't feel like a big deal back then, and honestly, it still doesn't now, but I am officially a college graduate with a B.S. from one of the best universities in the planet. Wild.

I do feel older. I do feel somewhat like an adult. I feel like what you would expect any recent graduate to feel like. I've been working in a lab since graduating, and it's great. I like what I do, I'm not too bad at what I do, and the work seems engaging and impactful enough. I'm planning on applying to PhD programs next month, so we'll see how that goes. 

The only regret I have about my undergraduate life is not being proactive enough about my career. I could have taken research more seriously earlier, I could have networked more, I could have done more internships, more projects, more classes... but I didn't. And honestly, it's fine. I have my excuses: when I got to campus sophmore year, I joined this dance team that took over my life. I was putting in 20 hours a week into it at one point and did poorly on multiple exams after staying up until god-knows-when for rehearsal. My time on the team wasn't the best experience in a lot of ways, but I met some of my best friends there and found something I actually wanted to be good at. Reflecting back now, I did have the time to do more career-related things, but my mind was elsewhere, so I didn't. I couldn't. 

But yeah. I'm done with school. I'm working. I'm applying to PhD programs. I'm dancing. I'm living. I'm breathing. I'm existing. I'm not sure if I'm doing any of it right--I'm not sure if I'm doing any of it at all. I'm not sure if I am. I'm not sure. I'm not. 

I'm gonna go to Korea in a few weeks for a little gap year. There's a long list of things I want to do while I'm there, and hopefully I'll get to do them all and write about them here. I vaugely remember starting the blog so that I could really internalize all the concepts I was learning by writing about them in a way other people could understand. A little twist on the Feynman technique, if you will. I haven't been writing a lot because I felt a weird pressure to write something *perfect*, but I'm realizing now that perfectionism hinders progress. There is no need for this blog to be "perfect" since the audience size is 0. So the new goal for this blog is to loosely write about things I'm learning, things I'm doing, and things I'm thinking about. 

I know I will regret publishing an unedited, hastily written blog entry like this one. But again, the goal isn't to be perfect, and I promised myself to publish today. So here it is. A little life update.